services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.80.2
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=root@example.com
      - ZO_ROOT_USER_PASSWORD=Complexpass#123
    ports:
      - "5080:5080"
    volumes:
      - openobserve-data:/data

  dogbridge:
    image: otel/opentelemetry-collector-contrib:0.151.0
    command: ["--config=/etc/dogbridge/config.yaml"]
    environment:
      - DOGBRIDGE_METRICS_LABEL_ALLOW_REGEX=.*
      - DOGBRIDGE_METRICS_LABEL_DENY_REGEX=^$
    volumes:
      - ./dogbridge-openobserve.yaml:/etc/dogbridge/config.yaml:ro
    ports:
      - "9126:8126"
      - "9125:8125/udp"
      - "5317:4317"
      - "5318:4318"
    depends_on:
      - openobserve

volumes:
  openobserve-data:
