receivers:
  filelog:
    include:
      - /var/log/pods/*/*/*.log
    start_at: end
    operators:
      - type: container
      - type: json_parser
        if: 'body matches "^\\{"'
        parse_from: body

processors:
  k8sattributes:
    auth_type: serviceAccount
  batch: {}

exporters:
  otlphttp/loki:
    endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [k8sattributes, batch]
      exporters: [otlphttp/loki]
