receivers:
  statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 10s
    enable_metric_type: true
    is_monotonic_counter: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1024
  transform/drop_high_cardinality:
    metric_statements:
      - context: datapoint
        statements:
          - delete_key(attributes, "claim_id")
          - delete_key(attributes, "raw_claim_id")
          - delete_key(attributes, "trace_id")
          - delete_key(attributes, "span_id")
          - delete_key(attributes, "request_id")
          - delete_key(attributes, "partition_key")
          - delete_key(attributes, "offset")
          - delete_key(attributes, "kafka_sequence")
          - delete_key(attributes, "runtime-id")
          - delete_key(attributes, "key_hash")
  batch: {}

exporters:
  prometheusremotewrite:
    endpoint: http://victoriametrics.monitoring.svc.cluster.local:8428/api/v1/write

service:
  pipelines:
    metrics:
      receivers: [statsd]
      processors: [memory_limiter, transform/drop_high_cardinality, batch]
      exporters: [prometheusremotewrite]
